use std::path::PathBuf;

use anyform_core::{InputPlugin, Options, StdLog};
use anyform_doc::PdfInput;

/// `PdfInput` needs `rust/scripts/fetch-pdfium.sh` to have run once (same
/// shape as `pdf_tests.rs` needing `fetch-chromium.sh`). Every fixture here
/// except `real-book.pdf` was generated by running this project's own
/// `PdfOutput` (bundled headless Chromium) over a small hand-written EPUB -
/// see `tests/fixtures/README.md` for the exact generation recipe per
/// fixture. `real-book.pdf` is the one genuinely third-party-produced PDF
/// in the set (a U.S. government document, public domain, never touched
/// this engine before), so the suite isn't only testing its own output's
/// idiosyncrasies.
fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures").join(name)
}

fn convert_to_epub(name: &str, pdf: &str) -> anyform_doc::DocumentIR {
    let output = std::env::temp_dir().join(format!("anyform-pdf-in-{name}-{}.epub", std::process::id()));
    let registry = anyform_doc::document_registry();
    registry.convert(&fixture(pdf), &output, &Options::new(), &StdLog).expect("PDF should convert to EPUB");
    let ir = anyform_doc::EpubInput.convert(&output, &Options::new(), &StdLog).expect("regenerated EPUB should parse");
    let _ = std::fs::remove_file(&output);
    ir
}

fn chapter_text(ir: &anyform_doc::DocumentIR) -> String {
    ir.spine.iter().map(|item| std::fs::read_to_string(ir.content_dir.join(&item.href)).unwrap_or_default()).collect::<Vec<_>>().join("\n")
}

#[test]
fn registry_dispatches_pdf_extension_to_this_plugin() {
    // Guards the wiring rather than the conversion, matching
    // kindle_tests.rs's equivalent - a missing extension entry would fall
    // through to "no input plugin registered" with a confusing error.
    assert!(PdfInput.extensions().contains(&"pdf"));
}

#[test]
fn minimal_text_pdf_splits_by_its_own_outline_with_real_text() {
    let ir = convert_to_epub("minimal-outline", "minimal-text.pdf");

    // minimal-text.pdf was rendered from minimal.epub via PdfOutput, which
    // builds a real PDF outline from the EPUB's TOC - so this should hit
    // the outline-preferred path in split_chapters, not the font-size
    // heuristic, giving exact chapter titles rather than guessed ones.
    let titles: Vec<&str> = ir.toc.iter().map(|n| n.title.as_str()).collect();
    assert!(titles.contains(&"Chapter One"), "titles: {titles:?}");

    let text = chapter_text(&ir);
    assert!(text.contains("This is the first chapter of the minimal fixture book"), "text: {text}");
    assert!(text.contains("This is the second chapter"), "text: {text}");
    // The two-space extraction bug (a real space glyph colliding with the
    // word-gap heuristic) must not regress.
    assert!(!text.contains("  "), "should not contain double spaces: {text}");
}

#[test]
fn heading_tiers_pdf_detects_headings_at_known_sizes_without_false_positives() {
    let ir = convert_to_epub("heading-tiers", "heading-tiers.pdf");
    let text = chapter_text(&ir);

    assert!(text.contains("<h1>The Big Title</h1>") || text.contains("The Big Title"), "text: {text}");
    assert!(text.contains("A Second Level Heading"), "text: {text}");
    // Regression pin for the false-positive this fixture originally caught:
    // a paragraph's own last line ("document.") averaged to ~11pt against
    // a ~9.5pt body, just barely crossing the *old* 1.15x heading-ratio
    // threshold - it must not be promoted to its own heading.
    assert!(!text.contains("<h3"), "\"document.\" should not be misdetected as a heading: {text}");
    assert!(text.contains("document."), "the sentence itself must still be present as body text: {text}");
}

#[test]
fn running_heads_pdf_strips_the_repeated_header_across_most_pages() {
    let ir = convert_to_epub("running-heads", "running-heads.pdf");
    let text = chapter_text(&ir);

    // running-heads.pdf has ~26 pages, each carrying a rendered header of
    // the book's own title. Unstripped, that title would appear ~26+
    // times; the real chapter heading (also titled identically, since the
    // fixture's own H1 matches the book title) legitimately contributes a
    // couple more. A low single-digit count proves stripping fired at
    // scale, not just on paper. Known limitation, disclosed rather than
    // chased further: on a page where the header sits unusually close to
    // the first body line, group_lines can merge them into one Line,
    // letting a mangled fragment survive - see tests/fixtures/README.md.
    let occurrences = text.matches("Running Head Test Book").count();
    assert!(occurrences <= 5, "expected running-head stripping to reduce ~26+ occurrences to a handful, got {occurrences}: {text}");
    assert!(occurrences >= 1, "the real chapter title should still legitimately appear at least once");
}

#[test]
fn two_column_pdf_is_rejected_with_a_specific_message() {
    let output = std::env::temp_dir().join(format!("anyform-pdf-in-twocol-{}.epub", std::process::id()));
    let registry = anyform_doc::document_registry();
    let result = registry.convert(&fixture("two-column.pdf"), &output, &Options::new(), &StdLog);
    let _ = std::fs::remove_file(&output);

    let err = result.expect_err("a two-column PDF must be rejected, not silently scrambled").to_string();
    assert!(err.contains("multi-column layout"), "got: {err}");
}

#[test]
fn scanned_pdf_is_rejected_with_a_specific_message() {
    let output = std::env::temp_dir().join(format!("anyform-pdf-in-scanned-{}.epub", std::process::id()));
    let registry = anyform_doc::document_registry();
    let result = registry.convert(&fixture("no-text-layer.pdf"), &output, &Options::new(), &StdLog);
    let _ = std::fs::remove_file(&output);

    let err = result.expect_err("an image-only PDF must be rejected, not emitted as an empty book").to_string();
    assert!(err.contains("no selectable text"), "got: {err}");
}

#[test]
fn encrypted_pdf_is_rejected_with_a_specific_message() {
    let output = std::env::temp_dir().join(format!("anyform-pdf-in-encrypted-{}.epub", std::process::id()));
    let registry = anyform_doc::document_registry();
    let result = registry.convert(&fixture("encrypted.pdf"), &output, &Options::new(), &StdLog);
    let _ = std::fs::remove_file(&output);

    let err = result.expect_err("a password-protected PDF must be rejected cleanly").to_string();
    assert!(err.contains("password-protected"), "got: {err}");
}

#[test]
fn unreadable_pdf_reports_a_useful_error() {
    let bogus = std::env::temp_dir().join(format!("anyform-not-a-real-{}.pdf", std::process::id()));
    std::fs::write(&bogus, b"this is definitely not a PDF").unwrap();
    let result = PdfInput.convert(&bogus, &Options::new(), &StdLog);
    let _ = std::fs::remove_file(&bogus);

    assert!(result.is_err(), "garbage bytes should not parse as a PDF");
}

#[test]
fn real_third_party_government_pdf_converts_with_readable_text() {
    // The one fixture in this set never produced by this engine's own
    // PdfOutput - a real, public-domain U.S. government PDF (see
    // tests/fixtures/README.md for provenance), so this test is the actual
    // quality bar, not just an internal round trip.
    let ir = convert_to_epub("real-book", "real-book.pdf");
    let text = chapter_text(&ir);

    assert!(text.contains("Constitution"), "text: {text}");
    assert!(text.contains("Congress"), "text: {text}");
    // The stylized-capital extraction artifact ("A merica") is a known,
    // disclosed limitation - not asserted against here - but the bulk of
    // the document must still be legible prose, not a single unbroken blob
    // or scrambled reading order.
    assert!(ir.spine.len() >= 1);
}

#[test]
fn one_pdf_input_plugin_reaches_every_output_format() {
    // The whole point of PdfInput per the plan's framing: Registry::convert
    // dispatches input/output plugins independently by extension, so this
    // one plugin should make minimal-text.pdf convertible to every format
    // the engine already supports, with zero per-output-format PDF-input
    // code anywhere else in the crate.
    let registry = anyform_doc::document_registry();
    let pid = std::process::id();
    for ext in ["epub", "txt", "html", "docx", "pdf"] {
        let output = std::env::temp_dir().join(format!("anyform-pdf-matrix-{pid}.{ext}"));
        registry
            .convert(&fixture("minimal-text.pdf"), &output, &Options::new(), &StdLog)
            .unwrap_or_else(|e| panic!("PDF -> .{ext} should succeed: {e}"));
        let bytes = std::fs::read(&output).unwrap_or_else(|e| panic!(".{ext} output should be readable: {e}"));
        let _ = std::fs::remove_file(&output);
        assert!(!bytes.is_empty(), ".{ext} output should not be empty");
    }
}

#[test]
fn pdf_input_output_epub_passes_epubcheck() {
    // Closes a real gap: every other check in this file inspects extracted
    // *text*, none confirms the EPUB container itself is spec-valid.
    // epub_output.rs's own doc comment already establishes that a
    // freshly-generated (not byte-copied) chapter set round-trips through
    // `EpubOutput` with zero epubcheck errors - PdfInput's synthesized
    // XHTML chapters are exactly that case (see pdf_layout.rs's
    // `render_chapter_xhtml`), so this should hold here too, unlike the
    // EPUB2-source case epub_output.rs documents as a known exception.
    //
    // Skips (not fails) when `epubcheck` isn't installed, matching this
    // project's existing "manual, not gated in CI" epubcheck practice
    // (see epub_output.rs) - this test upgrades that to automatic
    // whenever the tool happens to be present, without making it a hard
    // requirement for `cargo test` on a machine that doesn't have it.
    if std::process::Command::new("epubcheck").arg("--version").output().is_err() {
        eprintln!("epubcheck not found on PATH - skipping pdf_input_output_epub_passes_epubcheck (install with `brew install epubcheck` to run it)");
        return;
    }

    let output = std::env::temp_dir().join(format!("anyform-pdf-in-epubcheck-{}.epub", std::process::id()));
    let registry = anyform_doc::document_registry();
    registry.convert(&fixture("minimal-text.pdf"), &output, &Options::new(), &StdLog).expect("PDF should convert to EPUB");

    let result = std::process::Command::new("epubcheck").arg(&output).output().expect("epubcheck should run");
    let _ = std::fs::remove_file(&output);

    let report = format!("{}{}", String::from_utf8_lossy(&result.stdout), String::from_utf8_lossy(&result.stderr));
    assert!(result.status.success(), "epubcheck reported errors on a PDF-input-produced EPUB:\n{report}");
}

#[test]
fn concurrent_pdf_conversions_do_not_crash_pdfium() {
    // pdfium is not thread-safe on its own; pdfium-render's `thread_safe`
    // feature (enabled in Cargo.toml) serializes FFI calls behind its own
    // internal mutex - see pdfium.rs's module doc comment. This proves
    // that holds under real concurrent use, not just in single-threaded
    // `cargo test` runs (which already exercise multiple threads, but not
    // necessarily overlapping pdfium calls at the exact same instant).
    let handles: Vec<_> = (0..4)
        .map(|i| {
            std::thread::spawn(move || {
                let output = std::env::temp_dir().join(format!("anyform-pdf-concurrent-{i}-{}.epub", std::process::id()));
                let registry = anyform_doc::document_registry();
                let result = registry.convert(&fixture("minimal-text.pdf"), &output, &Options::new(), &StdLog);
                let _ = std::fs::remove_file(&output);
                result.is_ok()
            })
        })
        .collect();

    for h in handles {
        assert!(h.join().expect("thread should not panic"), "concurrent PDF conversion should succeed");
    }
}
