// Generated by cbindgen — see anyform-ffi/src/lib.rs. Regenerate with:
// cbindgen --crate anyform-ffi --output include/anyform.h
// (run manually after changing the FFI surface, not on every build)

#ifndef ANYFORM_FFI_H
#define ANYFORM_FFI_H



#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>

/**
 * Opaque cancellation handle for an in-flight `anyform_convert_start` call.
 */
typedef struct AnyformCancelToken AnyformCancelToken;

/**
 * Parses any registered input format — EPUB, Kindle-family, or PDF, not
 * just EPUB despite the name this replaced (`anyform_parse_epub`; it was
 * never actually EPUB-specific, since `registry.parse` dispatches by the
 * input path's extension the same way `registry.convert` does) — and
 * returns Book-info JSON (`{"status":"ok","book":{...}}` or
 * `{"status":"error","message":"..."}`) for the UI's file-loaded panel.
 * Caller must free the returned pointer with `anyform_free_string`.
 *
 * # Safety
 * `path` must be a valid, NUL-terminated UTF-8 C string.
 */
 char *anyform_parse_book(const char *path);

/**
 * Starts an async conversion on a background thread. `on_progress` may be
 * called zero or more times before `on_complete` fires exactly once.
 * Returns an owned `AnyformCancelToken*` the caller must eventually free
 * with `anyform_free_cancel_token` (after `on_complete` has fired, or
 * after cancelling).
 *
 * # Safety
 * `input_path`/`output_path`/`options_json` must be valid NUL-terminated
 * UTF-8 C strings. `progress_ctx`/`complete_ctx` are passed back verbatim
 * to the callbacks on whatever thread the conversion runs on — the caller
 * must ensure they stay valid and are safe to use from that thread until
 * `on_complete` fires.
 */

struct AnyformCancelToken *anyform_convert_start(const char *input_path,
                                                 const char *output_path,
                                                 const char *options_json,
                                                 void (*on_progress)(double fraction,
                                                                     const char *stage,
                                                                     void *ctx),
                                                 void *progress_ctx,
                                                 void (*on_complete)(int32_t success,
                                                                     const char *error_json,
                                                                     void *ctx),
                                                 void *complete_ctx);

/**
 * # Safety
 * `token` must be a pointer returned by `anyform_convert_start` that has
 * not yet been freed.
 */
 void anyform_cancel(struct AnyformCancelToken *token);

/**
 * # Safety
 * `token` must be a pointer returned by `anyform_convert_start`, not
 * already freed, and not used again afterward.
 */
 void anyform_free_cancel_token(struct AnyformCancelToken *token);

/**
 * # Safety
 * `s` must be a pointer returned by one of this crate's functions, not
 * already freed, and not used again afterward.
 */
 void anyform_free_string(char *s);

#endif  /* ANYFORM_FFI_H */
